source 'https://rubygems.org'

gem 'rspec'
gem 'sinatra'
gem 'rack'

group :development do #put it here only when runnimg the server
  gem 'pry'
  gem 'sinatra-reloader'
  gem 'guard'
  gem 'guard-rspec'
end

group :test do
  gem 'rack-test'
end